using System.Collections;
using System.Collections.Generic;
//using System.Random;
using UnityEngine;
using UnityEngine.UI;

public class ClickWord : MonoBehaviour
{
    static Respuesta[] palabras = {
        new Respuesta("Sci-fi",25),
        new Respuesta("Caballero",20),
        new Respuesta("Vaca",20),
        new Respuesta("Pistolas",20),
        new Respuesta("Escudo",10),
        new Respuesta("Espada",25),
        new Respuesta("Motor",35),
        new Respuesta("Rojo",25),
        new Respuesta("Villano/Villana",30),
        new Respuesta("Heroe",5),
        new Respuesta("Maldad",20),
        new Respuesta("Etapa",25),
        new Respuesta("Nivel",40),
        new Respuesta("Escena",35),
        new Respuesta("Protagonista",20),
        new Respuesta("Antagonista",35),
        new Respuesta("Temperatura",5),
        new Respuesta("Frio",25),
        new Respuesta("Calor",35),
        new Respuesta("Mascota",10),
        new Respuesta("Tenebroso",40),
        new Respuesta("Sol",40),
        new Respuesta("Luna",15),
        new Respuesta("Estrellas",5),
        new Respuesta("Dia",10),
        new Respuesta("Noche",40),
        new Respuesta("Teclado",5),
        new Respuesta("Microfono",30),
        new Respuesta("Audifonos",35),
        new Respuesta("Timidez",30),
        new Respuesta("Agradable",35),
        new Respuesta("Mofongo",10),
        new Respuesta("Burrito",20),
        new Respuesta("Responsable",25),
        new Respuesta("Valiente",15),
        new Respuesta("Astucia",35),
        new Respuesta("Honestidad",5),
        new Respuesta("Batman",35),
        new Respuesta("Disco",10),
        new Respuesta("Rap",15),
        new Respuesta("Rompecabezas",25),
        new Respuesta("Camara",25),
        new Respuesta("Mario",40),
        new Respuesta("Futbol",25),
        new Respuesta("Arbitro",30),
        new Respuesta("Festival",25),
        new Respuesta("Fiesta",20),
        new Respuesta("Arroz",10),
        new Respuesta("Policia",20),
        new Respuesta("Militar",30),
        new Respuesta("Guerra",15),
        new Respuesta("Rifle",35),
        new Respuesta("Tierra",15),
        new Respuesta("Piedra",5),
        new Respuesta("Madera",20),
        new Respuesta("Papel",30),
        new Respuesta("Verde",5),
        new Respuesta("Amarillo",15),
        new Respuesta("Comunidad",20),
        new Respuesta("Familia",25),
        new Respuesta("Dubstep",15),
        new Respuesta("Sol",25),
        new Respuesta("Chanclas",10),
        new Respuesta("Cartas",15),
        new Respuesta("Clonar",40),
        new Respuesta("Romper",15),
        new Respuesta("Construccion",20),
        new Respuesta("Vender",35),
        new Respuesta("Ametralladora",15),
        new Respuesta("Camioneta",35),
        new Respuesta("Doctor",35),
        new Respuesta("Puzzle",10),
        new Respuesta("Baile",40),
        new Respuesta("Sudoku",20),
        new Respuesta("Rambo",35),
        new Respuesta("Espi­as",15),
        new Respuesta("Cocinar",10),
        new Respuesta("Aliens",25),
        new Respuesta("Trampas",20),
        new Respuesta("Sigilo",5),
        new Respuesta("Bazuca",10),
        new Respuesta("Ragdoll",35),
        new Respuesta("Mariachis",25),
        new Respuesta("Pelo",20),
        new Respuesta("Tesoro",20),
        new Respuesta("Piratas",10),
        new Respuesta("Campesino",20),
        new Respuesta("Escopeta",25),
        new Respuesta("Selva",25),
        new Respuesta("Desierto",40),
        new Respuesta("Huracan",15),
        new Respuesta("Tormenta",30),
        new Respuesta("Crucigramas",35),
        new Respuesta("Destruir",35),
        new Respuesta("Demoler",35),
        new Respuesta("Cachetadas",10),
        new Respuesta("Emoticon",30),
        new Respuesta("Danza",15),
        new Respuesta("Victoria",35),
        new Respuesta("Perdida",5),
        new Respuesta("Nieve",5),
        new Respuesta("Edificios",40),
        new Respuesta("Lamentos",30),
        new Respuesta("Memes",30),
        new Respuesta("Bailar",15),
        new Respuesta("Grito",5),
        new Respuesta("Consola",20),
        new Respuesta("Medallas",40),
        new Respuesta("Premios",10),
        new Respuesta("Bandera",30),
        new Respuesta("Guitarra",40),
        new Respuesta("Colectibles",25),
        new Respuesta("Consumibles",20),
        new Respuesta("Tiempo",5),
        new Respuesta("Vidas",20),
        new Respuesta("Luna",35),
        new Respuesta("Televisor",20),
        new Respuesta("Retro",25),
        new Respuesta("Nostalgia",10),
        new Respuesta("Crimen",20),
        new Respuesta("Investigacion",30),
        new Respuesta("Dragon",40),
        new Respuesta("Casual",20),
        new Respuesta("Mito",15),
        new Respuesta("Fantasia",15),
        new Respuesta("Realidad",15),
        new Respuesta("Hamburgesa",40),
        new Respuesta("Refresco",15),
        new Respuesta("Planetas",35),
        new Respuesta("Espacio",15),
        new Respuesta("Galaxia",5),
        new Respuesta("Anime",10),
        new Respuesta("Caricaturas",40),
        new Respuesta("Simulador",40),
        new Respuesta("Alegria",15),
        new Respuesta("Tristeza",30),
        new Respuesta("Impacto",30),
        new Respuesta("Ego",15),
        new Respuesta("Egoista",40),
        new Respuesta("Monedas",35),
        new Respuesta("Dinero",20),
        new Respuesta("Chofer",15),
        new Respuesta("Chef",35),
        new Respuesta("Planta",20),
        new Respuesta("Explosivos",20),
        new Respuesta("Sobrevivir",30),
        new Respuesta("Melancolia",5),
        new Respuesta("Haiku",15),
        new Respuesta("Poema",25),
        new Respuesta("Escritura",35),
        new Respuesta("Libro",20),
        new Respuesta("Escultura",5),
        new Respuesta("Poder",15),
        new Respuesta("Invisibilidad",5),
        new Respuesta("Volar",40),
        new Respuesta("Gato",40),
        new Respuesta("Perro",15),
        new Respuesta("Muerte",25),
        // new Respuesta("DiseÃ±ar",10),
        new Respuesta("Portales",35),
        new Respuesta("Agua",15),
        new Respuesta("Bala",25),
        new Respuesta("Granada",15),
        new Respuesta("Bomba",20),
        new Respuesta("Lampara",15),
        new Respuesta("Seguridad",10),
        new Respuesta("Animatronicos",40),
        new Respuesta("Memoria",5),
        new Respuesta("Ayuda",5),
        new Respuesta("Piedra",15),
        new Respuesta("Suelo",20),
        new Respuesta("Heroe",15),
        new Respuesta("Bambu",35),
        new Respuesta("Sabana",10),
        new Respuesta("LLavero",10),
        new Respuesta("Aro",15),
        new Respuesta("Agua",10),
        new Respuesta("Pikachu",20),
        new Respuesta("Obsidiana",5),
        new Respuesta("Ruby",25),
        new Respuesta("Zafiro",10),
        new Respuesta("Garnet",10),
        new Respuesta("Gloton",20),
        new Respuesta("Rojo",30),
        new Respuesta("Azul",10),
        new Respuesta("Verde",15),
        new Respuesta("Oro",25),
        new Respuesta("Plata",5),
        new Respuesta("Cristal",25),
        new Respuesta("Blanco",30),
        new Respuesta("Negro",40),
        new Respuesta("Diamante",15),
        new Respuesta("Perla",5),
        new Respuesta("Platino",5),
        new Respuesta("Suika",35),
        new Respuesta("Saitama",35),
        new Respuesta("Robot",5),
        new Respuesta("Magma",25),
        new Respuesta("Viejo",15),
        new Respuesta("Rancho",15),
        new Respuesta("Montura",40),
        new Respuesta("Familia",15),
        new Respuesta("Fuerte",20),
        new Respuesta("Origen",15),
        new Respuesta("Escorpion",40),
        new Respuesta("Baul",10),
        new Respuesta("Cofre",30),
        new Respuesta("Esmeralda",25),
        new Respuesta("Esqueleto",35),
        new Respuesta("Manga",10),
        new Respuesta("Funda",5),
        new Respuesta("Rosa",35),
        new Respuesta("Valentin",20),
        new Respuesta("Estante",5),
        new Respuesta("Sarten",25),
        new Respuesta("Guante",25),
        new Respuesta("Tablet",15),
        new Respuesta("Pluma",30),
        new Respuesta("Lapiz",25),
        new Respuesta("Almoada",10),
        new Respuesta("Galleta",25),
        new Respuesta("Chaleco",30),
    };
    static System.Random rand  = new System.Random();
    Transform transform;
    Text texto;
    Vector2 destino = new Vector2(100,200);
    Vector2 velocidad;
    Respuesta palabraAsignada;
    bool moverse;
    // Start is called before the first frame update
    void Start()
    {
        transform = GetComponent<Transform>();
        texto = transform.GetChild(0).gameObject.GetComponent<Text>();
        ObtenerPalabraNueva();
        
    }

    public void EnviarMensajeAlGameManager(){
        GameManager.instance.RecibirRespuesta(palabraAsignada);
        ObtenerPalabraNueva();
        //Destroy(gameObject);
    }

    void ObtenerPalabraNueva(){
        int i = rand.Next(palabras.Length);
        palabraAsignada = palabras[i];
        texto.text = palabraAsignada.respuesta;
    }

    public Vector2 Vector3To2(Vector3 vec3){
        return new Vector2(vec3.x,vec3.y);
    }
}
